language: python
python:
- "2.7"
env:
- TOX_ENV=py2.6-django1.4
- TOX_ENV=py2.6-django1.5
- TOX_ENV=py2.6-django1.6
- TOX_ENV=py2.7-django1.4
- TOX_ENV=py2.7-django1.5
- TOX_ENV=py2.7-django1.6
install:
- pip install tox
script:
- tox -e $TOX_ENV
